apiVersion: apps/v1
kind: Deployment
metadata:
  name: hakonantonsen
  labels:
    app: hakonantonsen
    part: hakonantonsen
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hakonantonsen
      part: hakonantonsen
  template:
    metadata:
      labels:
        app: hakonantonsen
        part: hakonantonsen
    spec:
      containers:
      - name: hakonantonsen
        image: registry.mk8s.lanodispenser.no/hakonantonsen
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hakonantonsen
  labels:
    app: hakonantonsen
    part: hakonantonsen
spec:
  selector:
    part: hakonantonsen
  ports:
    - protocol: TCP
      name: "self-service"
      port: 80
      targetPort: 80