on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.mk8s.lanodispenser.no
      APP: hakonantonsen
    steps:
    - uses: actions/checkout@master
    - name: Set SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - run: |
        docker image build . -t $REGISTRY/$APP:${{ steps.vars.outputs.sha_short }}
        docker image push $REGISTRY/$APP:${{ steps.vars.outputs.sha_short }}
      
      
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          ./deployment.yaml
        images: |
          registry.mk8s.lanodispenser.no/hakonantonsen:${{ steps.vars.outputs.sha_short }}